name = "navigation-dataset-website"
main = "worker.js"
compatibility_date = "2023-08-01"

# Configure environment variables
[vars]
# These will be replaced with your actual values in the Cloudflare dashboard
WEBDAV_URL = ""
SHARE_ID = ""

# Configure settings for larger uploads
[site]
bucket = "./public"
