name = "navigation-dataset-website"
main = "worker.js"
compatibility_date = "2023-08-01"

# Configure environment variables
[vars]
# These will be replaced with your actual values in the Cloudflare dashboard
WEBDAV_URL = ""
SHARE_ID = ""

# Configure settings for larger uploads
[site]
bucket = "./public"

# Set limits for file uploads
[limits]
# Increase upload limits (100MB for paid workers, 25MB for free)
upload_size = 104857600
cpu_ms = 10